export const ID = {
  title: 'Aplikasi Catatan',
  loginDesc: 'Yuk, login untuk menggunakan aplikasi.',
  loginNoAccount: 'Belum punya akun? ',
  loginCreateAccount: 'Daftar disini',
  RegisterDesc: 'Isi form untuk mendaftar akun.',
  registerHaveAccount: 'Sudah punya akun? ',
  registerLoginAccount: 'Login di sini',
  archive: 'Terarsip',
  homepage: 'Catatan Aktif',
  search: 'Cari berdasarkan judul ...',
  loading: 'Mengambil note . . .',
  empty: 'Tidak ada catatan',
  archiveDesc: 'Catatan Arsip',
};
export const EN = {
  title: 'Notes App',
  loginDesc: 'Login to use app, please.',
  loginNoAccount: 'Don\'t have an account? ',
  loginCreateAccount: 'Register here',
  RegisterDesc: 'Fill the form to register account.',
  registerHaveAccount: 'Already have an account? ',
  registerLoginAccount: 'Login here',
  archive: 'Archived',
  homepage: 'Active Note',
  search: 'Search by title ...',
  loading: 'Fetching notes . . .',
  empty: 'No notes',
  archiveDesc: 'Archived Notes',
};
